### PR TITLE
Update README.md

### LINKED ISSUE #58: Update README.md to reflect project development
## Objectives
- README.md display more precise and up-to-date project information
- All relevant libraries and packages are linked and referenced
- Installation and deployment instructions are linked to relevant wiki pages
- Automatically build and deploy alpha-1 release for macOS, Windows and Ubuntu

## Reading
- [Article with a very nice template](https://meakaakka.medium.com/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3)

## Notable examples:
- [Markdownify](https://github.com/amitmerchant1990/electron-markdownify#readme)
- [Home Assist-Config](https://github.com/CCOSTAN/Home-AssistantConfig#readme) - This one is plenty ... maybe too much
- [ML-VC](https://github.com/iterative/dvc#readme) - This one is very nice
- [Zircon](https://github.com/Hexworks/zircon#readme) - Has many interesting ideas

### PR DESCRIPTION
**Pull request by nikalc**
- Updates readme document reflecting
current project progress

- Suggest more updates as project goes

Resolves #58

### CODE REVIEW

**Review by axe007 — APPROVED** [review]
Great update. Now let's do the Manual control page instructions. 

Thanks.

**Comment by kam56** [comment]
YES, time to update the boring README. 

I think you should delete the last two commit messages. Use git rebase -i HEAD~3

**Comment by nikalc** [comment]
> 
> 
> YES, time to update the boring README.
> 
> I think you should delete the last two commit messages. Use git rebase -i HEAD~3

Thanks. Fixed it. GitHub Desktop keep adding one more commit with this extra long subject. Not sure why.

**Comment by kam56** [comment]
yeah, I also had the same problem, last time.

**Pull request merged**
