### PR TITLE
Implement manual control buttons

### LINKED ISSUE #63: [Task] Manual control page update
## Tasks
- Update Manual control page layout
- Improve CSS and looks
- Connect MQTT communication script
- Update control button actions

### PR DESCRIPTION
**Pull request by axe007**
## Tasks completed:
- Completed layout update for manual control page
- Implement control pad buttons
- Implement camera stream update

## Next steps:
- Needs to refactor command console and serial feed
- Refactor RGB conversion part

Resolves #63

### CODE REVIEW

**Review by OneMoreOreo — APPROVED** [review]
Very Nice!

Just going to add some code to the buttons to publish message.

**Comment by kam56** [comment]
Great job I would say. It looks unbelievably nice. 
So one issue I see is when checking other pages while they connected it refreshes automatically. Is it because we have not added the functions yet?

**Comment by axe007** [comment]
> Great job I would say. It looks unbelievably nice.
> So one issue I see is when checking other pages while they connected it refreshes automatically. Is it because we have not added the functions yet?

I think that one is on @OneMoreOreo 
Manual control console window tends to reload entire page on wrong command while it tries to scroll down to show last "text". I will look into that. That part needs to be refactored.

How MQTT connect, power up, satellite, camera, and overall feel?

**Comment by kam56** [comment]
I like the way all the very important functions are packed on the same page. Besides, they function very smoothly. Oh I just noticed the pop-up that the rover is not powered. 
So, It is perfectly what we had planned.

**Pull request merged**
