### PR TITLE
Create accordion for help menu

### LINKED ISSUE #5: 1.7 Help Menu
As a user I want to have the instructions on how to use the website, under the main menu, so that it is easy for me to choose the right option and use the software correctly.

Acceptance criteria: Home page and help menu are implemented.

### PR DESCRIPTION
**Pull request by nikalc**
Create accordion for help menu

Implement accordion for help menu to improve readability, interface and avoid clustering.

Resolves #5

Co-Authored-By: Anwar Ramadi <70433638+ramadi-a@users.noreply.github.com>

### CODE REVIEW

**Review by ramadi-a — APPROVED** [review]
Looks good

**Review by axe007 — CHANGES_REQUESTED** [review]
Please check why style.css indentations are being replaced with 2 spaces instead of 1 Tab.

Accordian menu needs to similar ~300px width and needs to be inside "col-left" div. It is outside right underneath Title and breaks page layout.

**Comment by ramadi-a** [comment]
indentations are one tab actually, but when you check indentations in GitHub it will appears as two spaces. I will move the accordion menus to col-left and fix it

**Review by OneMoreOreo — APPROVED** [review]
Looks nice.

Are all menus closed by default?

**Review by axe007 — APPROVED** [review]
Works good.

@nikalc @ramadi-a @OneMoreOreo @kam56 
Please note that for all project code, js, css or json, we are using 1-tab per level of code style.
Make sure you have it set properly on your IDE. Thanks.

**Pull request merged**
