### PR TITLE
# Clean up the frontend up code

### PR DESCRIPTION
**Pull request by kam56**
* Delete the parts which are not used anymore
* Correct indentation
* Fix the bug on the manual control page

## Why was it needed?
* Housekeeping becomes difficult when
new code is added

### CODE REVIEW

**Review by axe007 — CHANGES_REQUESTED** [review]
Hi Kamila,

Could you please try rebasing this "updates-from-sensors" branch to current master. It seems to miss several merged and behind the master so that it is causing some conflicts.
Also .gitignore is not up-to-date etc.

**Comment by kam56** [comment]
> Hi Kamila,
> 
> Could you please try rebasing this "updates-from-sensors" branch to current master. It seems to miss several merged and behind the master so that it is causing some conflicts.
> Also .gitignore is not up-to-date etc.

I made sure to keep the branch up to date. But apparently, I have worked on an old local folder. I will try again.

**Comment by kam56** [comment]
I am closing this pull request because I had accidentally updated an old branch that had the same name as the new branch I  created locally. I will create a new branch and add the updates to that.

**Comment by axe007** [comment]
Also we chose to close the PR instead of rebasing, as some of updates in these commits were already fixed in a different way. So merging rebased branch still would not help much.

**Pull request closed without merging**
